# Generated by Django 2.0 on 2018-05-01 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180501_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastusercontext',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.UserTelegram'),
        ),
    ]
